news_sites:
  eluniversal:
    url: 'https://www.eluniversal.com.mx'
    queries:
      homepage_article_links : '.field-content a'
      article_title: '.pane-content h1'
      article_body: '.field-name-body'
      article_journalist: ''
      article_category: ''
  elcomercio:
    url: 'https://elcomercio.pe'
    queries: 
      homepage_article_links: '.grid a'
      article_title: '.sht h1'
      article_body: '.story-contents__content section'
      article_journalist: '.'
      article_category: '.oflow-h a'
  marca:
    url: "https://www.marca.com"
    queries:
      homepage_article_links: '.main a'
      article_title: '.titles h1'
      article_body: '.row.content.cols-30-70 p'
      article_journalist: ''
      article_category: ''
  newyorktimes:
    url: "https://www.nytimes.com/es/"
    queries:
      homepage_article_links: '.css h2 a'
      article_title: '.css h1'
      article_body: '.css p'
      article_journalist: ''
      article_category: ''